const defaultCategories = [
  {"id":"0","catName":"Utilities","catAncestry":""},
  {"id":"1","catName":"Housing","catAncestry":""},
  {"id":"2","catName":"Healthcare","catAncestry":""},
  {"id":"3","catName":"Savings","catAncestry":""},
  {"id":"4","catName":"Clothing","catAncestry":""},
  {"id":"5","catName":"Hobbies","catAncestry":""},
  {"id":"6","catName":"Transportation","catAncestry":""},
  {"id":"7","catName":"Debt","catAncestry":""},
  {"id":"8","catName":"Food & Drink","catAncestry":""},
  {"id":"9","catName":"Electricity","catAncestry":"0"},
  {"id":"10","catName":"Gas","catAncestry":"0"},
  {"id":"11","catName":"Water","catAncestry":"0"},
  {"id":"12","catName":"Internet","catAncestry":"0"},
  {"id":"13","catName":"Mortgage","catAncestry":"1"},
  {"id":"14","catName":"Repairs","catAncestry":"1"},
  {"id":"15","catName":"Furniture","catAncestry":"1"},
  {"id":"16","catName":"Appliances","catAncestry":"1"},
  {"id":"17","catName":"Dental","catAncestry":"2"},
  {"id":"18","catName":"Health Insurance","catAncestry":"2"},
  {"id":"19","catName":"Life Insurance","catAncestry":"2"},
  {"id":"20","catName":"Medical","catAncestry":"2"},
  {"id":"21","catName":"Socializing","catAncestry":"5"},
  {"id":"22","catName":"Crafting","catAncestry":"5"},
  {"id":"23","catName":"Brewing","catAncestry":"5"},
  {"id":"24","catName":"Car Insurance","catAncestry":"6"},
  {"id":"25","catName":"Car Maintenance","catAncestry":"6"},
  {"id":"26","catName":"Gasoline","catAncestry":"6"},
  {"id":"27","catName":"Carryout","catAncestry":"8"},
  {"id":"28","catName":"Bars","catAncestry":"8"},
  {"id":"29","catName":"Restaurants","catAncestry":"8"},
  {"id":"30","catName":"Groceries","catAncestry":"8"},
  {"id":"31","catName":"Fines & Fees","catAncestry":""},
  {"id":"32","catName":"Gifts","catAncestry":""},
]

export function getDefaultCategories () {
  return defaultCategories
}
